apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jupyterhub-home-nfs.home-nfs.fullname" . }}
  labels:
    {{- include "jupyterhub-home-nfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  {{/* Quoting is important as empty string is treated differently than null here */}}
  storageClassName: {{ .Values.persistentVolume.storageClass | quote }}
  {{- if or .Values.eks.enabled .Values.gke.enabled .Values.openstack.enabled}}
  volumeName: {{ .Release.Name }}-{{ include "jupyterhub-home-nfs.home-nfs.fullname" . }}
  {{- end }}
